---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
  run_list:
  - recipe[apt]
- name: canonical-ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true
    customize:
       memory: 512
  run_list:
  - recipe[apt]

suites:
- name: fullstack
  run_list:
  - recipe[platform_packages]
  - recipe[orch::fullstack]
  - recipe[dummy_app]
  attributes:
    platform_packages:
      pkgs:
        - name: curl
    postgresql:
      password:
        postgres: 'masterpassword'
    orch:
      apps:
        - name: dummy_app
          user: vagrant
          port: 8000
          ruby_version: 1.9.3-p327
          db_password: flargle
          db_type: postgres
          servers:
            - 'localhost:8000'
          environment:
          -
            - RAILS_ENV
            - production
